### ISSUE TITLE
Can't find CommentNode via `find` method.

### ISSUE THREAD

**Issue by gtors** [PyCQA/redbaron#117]
**Env:**

Python 3.5.2
RedBaron 0.6.1

**Example:**

``` python
r = RedBaron("""
class X:
    # test
    def __init__(self): 
        pass
""")
r.find('comment') # returns None
r.find_all('comment') # returns NodeList with len == 1
```

**Expected behavior:**

`r.find('comment')` - should return node with comment

**Comment by b5y** [comment]
change 'comment' to 'CommentNode' and it will find it

**Comment by gtors** [comment]
Thx. But why `find_all` works  and `find` not? Looks a bit strange  :)

**Comment by gtors** [comment]
> change 'comment' to 'CommentNode' and it will find it

No. It's also not works.

```
r = RedBaron('''
class X:
    # fsddfsf
    pass
''')
r.find('CommentNode') # returns None
r.find('class').find('CommentNode') # returns None
```

**Comment by b5y** [comment]
@gtors ```find``` might not work for CommentNode because of famous bug with comments on ```baron``` level which inherits to ```RedBaron```. I have tried to fix this bug but do not have enough time to finish it (it is very nasty bug). ```find``` just gets first node which corresponds to the given properties in arguments (such as ```name``` when you find for ```class``` of ```def```, for example).

From your first sample:
```python
from redbaron import RedBaron

r = RedBaron("""
class X:
    # test
    def __init__(self):
        pass
""")

print r.find_all('CommentNode')
```

outputs:

```0   <CommentNode path=[1, 'value', 1, 'formatting', 0], "# test" 4335792016, on EndlNode 4335791760>```

Try find_all with index if you are searching for specific comment. For instance: r.find_all('CommentNode')[0].

From the second sample:

```python
from redbaron import RedBaron

r = RedBaron('''
class X:
    # fsddfsf
    pass
''')

print r.find('ClassNode').find_all('CommentNode')
```

By the way, ```RedBaron``` has one of the best [documentations](https://redbaron.readthedocs.io/en/latest/) I have ever seen.
