### ISSUE TITLE
'utils.in_a_shell()' : stack overflow.

### ISSUE THREAD

**Issue by petspats** [PyCQA/redbaron#119]
Happens on Pycharm 2016.2.2, works fine on console.
Version: 0.6.1 (latest from pip)
Example:

``` python
from redbaron import RedBaron
import textwrap
code = textwrap.dedent("""\
    def a():
        pass""")
red = RedBaron(code)[0]
red.value.insert(0, 'a') # <- problem here
```

Result:

```
Fatal Python error: Cannot recover from stack overflow.

Current thread 0x00007fcd31630700 (most recent call first):
  File "python3.5/site-packages/redbaron/utils.py", line 38 in in_a_shell
  File "python3.5/site-packages/redbaron/base_nodes.py", line 946 in __repr__
  File "python3.5/collections/__init__.py", line 1081 in index
  File "python3.5/site-packages/redbaron/base_nodes.py", line 119 in get_holder_on_attribute
  File "python3.5/site-packages/redbaron/base_nodes.py", line 50 in __init__
  File "python3.5/site-packages/redbaron/base_nodes.py", line 840 in path
  File "python3.5/site-packages/redbaron/base_nodes.py", line 951 in __repr__
  File "python3.5/collections/__init__.py", line 1081 in index
  File "python3.5/site-packages/redbaron/base_nodes.py", line 119 in get_holder_on_attribute
  File "python3.5/site-packages/redbaron/base_nodes.py", line 50 in __init__
  File "python3.5/site-packages/redbaron/base_nodes.py", line 840 in path
  File "python3.5/site-packages/redbaron/base_nodes.py", line 951 in __repr__
```

I have currently set 'utils.in_a_shell()' default return to True instead of False. This fixes the problem but i am not sure if this is a correct way to do it.

Thanks for the good work :)

**Comment by b5y** [comment]
You should avoid running large programs in PyCharm using ```RedBaron```. I have had this [error](http://stackoverflow.com/questions/8177073/python-maximum-recursion-depth-exceeded) and solved it running program via terminal (without ```import sys```). PyCharm has some memory usage restrictions and therefore has some problems. There is "binding" to terminal on the bottom of PyCharm window. Just use it. :)

**Comment by petspats** [comment]
The snippet i posted is just minimal test to produce this error, i am not using PyCharm as a terminal replacement.
Problem is related to infinite recursion, which i would classify as a bug.

**Comment by b5y** [comment]
I did not suggest you to use terminal instead of PyCharm. The advice was in running program, not in implementing.

Actually, it is not a bug. I have tried with Python 2.7.12 and what I got if I run in PyCharm (last two lines):
```
return Path(self)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Is is exactly what I mentioned on my previous comment.

And what I get if I run via terminal:
```python

def a():
    a
    pass
```

So, it is the same thing as with Python 3.5 except error output.
The initial purpose of ```RedBaron``` was using it in terminal (IPython).

I don't think that it is a bug. If you try to add this line on your code:

```python
redbaron.DEBUG = True
```

Everything will work fine.

**Comment by petspats** [comment]
Clearly if i am using some development environment i want to also run code in that environment, think about debugging for example. Furthermore i have all my unit-tests failing because i am using pycharm's test integration.

Setting the DEBUG flag fixes the problem, but i believe some permanent fix is required as  this issue will very likely rise for other people as well.

**Comment by b5y** [comment]
There are another solutions:

1) Changing IDE
2) Debuging with pdb (using terminal)
2) Splitting project to multiple pieces of code during testing/debugging (using PyCharm)

```RedBaron``` project exists since early 2014. I don't think that we are only two persons who had this problem before. For instance, [this large project](https://github.com/kayhayen/Nuitka) uses ```RedBaron```.

**Comment by ibizaman** [comment]
@petspats so just running the program you showed produces that much recursion? I didn't check the code for this issues but that seems indeed like _way_ too much recursion for such a "simple" parsing.
And although @b5y is right in that you could use something else to run the baron code, I totally understand you don't want that as I wouldn't want that either.
